- name: Install packages
  hosts: servers
  become: yes

  vars:
    packages_to_install:
      - tree
      - zip
      - unzip
      - jq
      - wget
      - apache2

  tasks:
    - name: show packeges 
      debug:
        msg: "installing {{ item }}"
      loop: "{{ packages_to_install }}"  
      

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"  
      when: ansible_facts["distribution"] == "Ubuntu"  
